POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "user",
    "password": "user123",
    "confirm_password": "user123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "user",
    "password": "user123"
}

###
GET http://localhost:5000/token

###
DELETE http://localhost:5000/logout