POST http://localhost:5000/register
Content-Type: application/json

{
    "username": "Wijdan",
    "password": "Wijdan123",
    "confirm_password": "Wijdan123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}

###
GET http://localhost:5000/token

###---
DELETE http://localhost:5000/delete-note/12
Content-Type: application/json
Authorization: Bereer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiIxMjMiLCJpYXQiOjE3NDY2MzgzMzIsImV4cCI6MTc0NjYzODM1Mn0.sd_jM7cb040cxUUAKpSaWTj9f1xr9dpGoQmk3YGdIAo

###
PUT http://localhost:5000/update-note/
Content-Type: application/json
Authorization: Bereer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiIxMjMiLCJpYXQiOjE3NDY2MzgzMzIsImV4cCI6MTc0NjYzODM1Mn0.sd_jM7cb040cxUUAKpSaWTj9f1xr9dpGoQmk3YGdIAo

{
  "title": "Test Ubah",
  "content": "Ini"
}