steps:
  # Step 1: Install dependencies (dengan cache lokal via volume)
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    dir: "notes_fe"

  # Step 2: Deploy to App Engine
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "notes_fe"

options:
  logging: CLOUD_LOGGING_ONLY
