steps:
# 1. Install dependencies
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'notes_fe'

# 2. Build Vite frontend
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'notes_fe'

# 3. Deploy hasil build ke App Engine
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['app', 'deploy', '--quiet']
  dir: 'notes_fe'
