options:
  logging: CLOUD_LOGGING_ONLY
  cache:
    paths:
      - node_modules/
      - .npm/

steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'notes_fe'

- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']
  dir: 'notes_fe'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['app', 'deploy', '--quiet']
  dir: 'notes_fe'