options:
  logging: CLOUD_LOGGING_ONLY
cache:
  paths:
    - "notes_fe/node_modules"
    - "notes_fe/.npm"

steps:
  - name: "gcr.io/cloud-builders/npm"
    entrypoint: bash
    args:
      - -c
      - |
        if [ ! -d "node_modules" ]; then
          echo "Installing dependencies..."
          npm ci
        else
          echo "Skipping npm install, node_modules exists."
        fi
    dir: "notes_fe"

  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    dir: "notes_fe"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args: ["app", "deploy", "--quiet"]
    dir: "notes_fe"
